In [1]:
import numpy as np
a = np.array([1, 2, 3])    # 넘파이로 배열 만들기
a

array([1, 2, 3])

In [2]:
b = np.array([5, 6, 7])
b

array([5, 6, 7])

In [3]:
a * b    # 배열 같은 경우 짝 지어서 곱해준다

array([ 5, 12, 21])

In [4]:
np.dot(a, b)    # 단순 곱을 짝 지어서 더한다

38

In [5]:
a @ b    # 위와 동일한 연산

38

In [6]:
np.einsum('i, i', a, b)    # a의 i번째와 b의 i번째를 곱해서 더해라 - 위와 동일한 결과

38

In [9]:
np.einsum('j, j', a, b)

38

# 1. 행렬

In [10]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [12]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d = np.array([[1, 2], [3, 4], [5, 6]])
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.dot(c, d)    # 123-135, 123-246 / 456-135, 456-246

array([[22, 28],
       [49, 64]])

In [16]:
c @ d

array([[22, 28],
       [49, 64]])

In [17]:
c[0, :]

array([1, 2, 3])

In [20]:
d[:, 0]    # d의 0번째 열 출력

array([1, 3, 5])

In [22]:
c[0, :] @ d[:, 0]

22

In [23]:
np.einsum('ik, kj -> ij', c, d)

array([[22, 28],
       [49, 64]])