In [1]:
import tensorflow as tf
# AutoTokenizer : 미리 학습된 토크나이저
# TFAutoModelForCausalLM : Language Model 언어 모형
from transformers import TFAutoModelForCausalLM, AutoTokenizer

In [2]:
tokenizer = AutoTokenizer.from_pretrained("xlnet-base-cased")

In [3]:
model = TFAutoModelForCausalLM.from_pretrained("xlnet-base-cased")

All model checkpoint layers were used when initializing TFXLNetLMHeadModel.

All the layers of TFXLNetLMHeadModel were initialized from the model checkpoint at xlnet-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetLMHeadModel for predictions without further training.


In [4]:
tokenizer.vocab_size

32000

In [5]:
vocab = tokenizer.get_vocab()
vocab

{'▁reliable': 5401,
 '▁Hawaiian': 17782,
 '▁cod': 20134,
 '▁Marie': 9052,
 '▁Chattanooga': 31061,
 'behaved': 27547,
 '▁handkerchief': 31424,
 '▁amalgam': 22294,
 '▁hall': 3601,
 '▁hostility': 20410,
 'jima': 25253,
 '▁competency': 30192,
 '▁violent': 4400,
 '▁subjects': 5605,
 '▁sale': 1634,
 'LY': 10775,
 '▁accuses': 19177,
 '▁delve': 28175,
 'marriage': 30537,
 '▁gaps': 16047,
 '▁wires': 17203,
 '▁Porto': 18961,
 '▁feeble': 30678,
 '▁income': 1378,
 'rica': 19439,
 '▁qualification': 12641,
 '▁Sym': 16099,
 '3:30': 27039,
 '▁pigs': 17084,
 '▁failure': 2513,
 '▁Sutton': 19435,
 '▁distress': 12745,
 '▁guy': 2035,
 '▁Province': 3311,
 '▁thoughtful': 16783,
 '▁girls': 2537,
 '▁crucial': 4366,
 'eem': 14979,
 '▁prep': 21612,
 '▁themselves': 1038,
 'gin': 5043,
 '▁portraying': 26361,
 '▁erotic': 23993,
 '▁twitter': 30476,
 '▁Morton': 18812,
 '▁tycoon': 24332,
 '▁saving': 6144,
 '▁Shipping': 15281,
 '▁emphasize': 11300,
 '2,000': 8114,
 '▁Cur': 6370,
 '▁devices': 3259,
 '▁jazz': 7004,
 '▁di

In [6]:
id2word = {i:word for word, i in vocab.items()}
id2word

{5401: '▁reliable',
 17782: '▁Hawaiian',
 20134: '▁cod',
 9052: '▁Marie',
 31061: '▁Chattanooga',
 27547: 'behaved',
 31424: '▁handkerchief',
 22294: '▁amalgam',
 3601: '▁hall',
 20410: '▁hostility',
 25253: 'jima',
 30192: '▁competency',
 4400: '▁violent',
 5605: '▁subjects',
 1634: '▁sale',
 10775: 'LY',
 19177: '▁accuses',
 28175: '▁delve',
 30537: 'marriage',
 16047: '▁gaps',
 17203: '▁wires',
 18961: '▁Porto',
 30678: '▁feeble',
 1378: '▁income',
 19439: 'rica',
 12641: '▁qualification',
 16099: '▁Sym',
 27039: '3:30',
 17084: '▁pigs',
 2513: '▁failure',
 19435: '▁Sutton',
 12745: '▁distress',
 2035: '▁guy',
 3311: '▁Province',
 16783: '▁thoughtful',
 2537: '▁girls',
 4366: '▁crucial',
 14979: 'eem',
 21612: '▁prep',
 1038: '▁themselves',
 5043: 'gin',
 26361: '▁portraying',
 23993: '▁erotic',
 30476: '▁twitter',
 18812: '▁Morton',
 24332: '▁tycoon',
 6144: '▁saving',
 15281: '▁Shipping',
 11300: '▁emphasize',
 8114: '2,000',
 6370: '▁Cur',
 3259: '▁devices',
 7004: '▁jazz',
 7898

In [7]:
sequence = f'Once upon a time, there was'

In [10]:
input_ids = tokenizer.encode(sequence, return_tensors='tf')

In [11]:
input_ids

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1977,  975,   24,   92,   19,  105,   30,    4,    3]])>

In [12]:
id2word[1977]

'▁Once'

In [13]:
result = model(input_ids)

In [14]:
result

TFXLNetLMHeadModelOutput(loss=None, logits=<tf.Tensor: shape=(1, 9, 32000), dtype=float32, numpy=
array([[[-20.825804, -34.659046, -34.44884 , ..., -27.78459 ,
         -30.744413, -35.803753],
        [-22.204262, -37.77572 , -37.351643, ..., -30.710463,
         -29.529594, -36.7091  ],
        [-25.660414, -41.25014 , -40.929314, ..., -33.947014,
         -31.24387 , -37.114742],
        ...,
        [-19.059734, -33.74291 , -33.51809 , ..., -25.464384,
         -26.77374 , -34.887234],
        [-16.845284, -33.212414, -32.90258 , ..., -25.412703,
         -25.436674, -33.201527],
        [-14.362107, -31.21588 , -30.875046, ..., -23.44358 ,
         -22.542234, -30.336588]]], dtype=float32)>, mems=(<tf.Tensor: shape=(9, 1, 768), dtype=float32, numpy=
array([[[ 0.06072645, -0.00645501, -0.08168449, ..., -0.04846613,
          0.00395189, -0.05275054]],

       [[-0.03548658,  0.06003479, -0.05184234, ..., -0.01261167,
          0.01167144, -0.02942811]],

       [[-0.02292611,  0.01

In [15]:
logits = result[0]
logits

<tf.Tensor: shape=(1, 9, 32000), dtype=float32, numpy=
array([[[-20.825804, -34.659046, -34.44884 , ..., -27.78459 ,
         -30.744413, -35.803753],
        [-22.204262, -37.77572 , -37.351643, ..., -30.710463,
         -29.529594, -36.7091  ],
        [-25.660414, -41.25014 , -40.929314, ..., -33.947014,
         -31.24387 , -37.114742],
        ...,
        [-19.059734, -33.74291 , -33.51809 , ..., -25.464384,
         -26.77374 , -34.887234],
        [-16.845284, -33.212414, -32.90258 , ..., -25.412703,
         -25.436674, -33.201527],
        [-14.362107, -31.21588 , -30.875046, ..., -23.44358 ,
         -22.542234, -30.336588]]], dtype=float32)>

In [16]:
logits.shape

TensorShape([1, 9, 32000])

In [17]:
next_token_logits = logits[:, -1, :]

In [18]:
next_token_logits

<tf.Tensor: shape=(1, 32000), dtype=float32, numpy=
array([[-14.362107, -31.21588 , -30.875046, ..., -23.44358 , -22.542234,
        -30.336588]], dtype=float32)>

In [19]:
next_token_logits.shape

TensorShape([1, 32000])

In [20]:
tf.nn.softmax(next_token_logits)

<tf.Tensor: shape=(1, 32000), dtype=float32, numpy=
array([[1.5699961e-05, 7.5231190e-13, 1.0578402e-12, ..., 1.7859298e-09,
        4.3985966e-09, 1.8124639e-12]], dtype=float32)>

In [22]:
top = tf.math.top_k(next_token_logits, k=10)
top

TopKV2(values=<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-5.378241 , -5.5225034, -5.7933207, -5.8336697, -6.059229 ,
        -6.462745 , -6.725597 , -7.0102534, -7.014065 , -7.0365496]],
      dtype=float32)>, indices=<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 49,  17,  19,  66,   9, 545,  24, 125,  30,  21]])>)

In [23]:
top.indices

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 49,  17,  19,  66,   9, 545,  24, 125,  30,  21]])>

In [25]:
for i in top.indices[0].numpy().tolist():
    print(id2word[i])

▁or
▁
,
d
.
▁ever
▁a
▁just
▁was
▁and
