In [1]:
from transformers import pipeline

In [2]:
nlp = pipeline("fill-mask")

No model was supplied, defaulted to distilroberta-base (https://huggingface.co/distilroberta-base)


Downloading:   0%|          | 0.00/480 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/465M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFRobertaForMaskedLM.

All the layers of TFRobertaForMaskedLM were initialized from the model checkpoint at distilroberta-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForMaskedLM for predictions without further training.


Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

In [3]:
# 마스크 토큰
nlp.tokenizer.mask_token

'<mask>'

In [7]:
f'Pizze is my {nlp.tokenizer.mask_token}'

'Pizze is my <mask>'

In [9]:
nlp(f'Pizze is my {nlp.tokenizer.mask_token} food')

[{'score': 0.47562044858932495,
  'token': 2674,
  'token_str': ' favorite',
  'sequence': 'Pizze is my favorite food'},
 {'score': 0.17703180015087128,
  'token': 5548,
  'token_str': ' favourite',
  'sequence': 'Pizze is my favourite food'},
 {'score': 0.17194382846355438,
  'token': 5863,
  'token_str': ' comfort',
  'sequence': 'Pizze is my comfort food'},
 {'score': 0.022090883925557137,
  'token': 3366,
  'token_str': ' dream',
  'sequence': 'Pizze is my dream food'},
 {'score': 0.017506703734397888,
  'token': 6543,
  'token_str': ' signature',
  'sequence': 'Pizze is my signature food'}]

In [11]:
nlp(f"Pizzs is {nlp.tokenizer.mask_token} my {nlp.tokenizer.mask_token} food")

[[{'score': 0.07702243328094482,
   'token': 122,
   'token_str': ' now',
   'sequence': '<s>Pizzs is now my<mask> food</s>'},
  {'score': 0.059075310826301575,
   'token': 460,
   'token_str': ' always',
   'sequence': '<s>Pizzs is always my<mask> food</s>'},
  {'score': 0.048316530883312225,
   'token': 2299,
   'token_str': ' definitely',
   'sequence': '<s>Pizzs is definitely my<mask> food</s>'},
  {'score': 0.04578939080238342,
   'token': 5072,
   'token_str': ' basically',
   'sequence': '<s>Pizzs is basically my<mask> food</s>'},
  {'score': 0.04288775846362114,
   'token': 1153,
   'token_str': ' probably',
   'sequence': '<s>Pizzs is probably my<mask> food</s>'}],
 [{'score': 0.4267764091491699,
   'token': 2674,
   'token_str': ' favorite',
   'sequence': '<s>Pizzs is<mask> my favorite food</s>'},
  {'score': 0.20855730772018433,
   'token': 5548,
   'token_str': ' favourite',
   'sequence': '<s>Pizzs is<mask> my favourite food</s>'},
  {'score': 0.1770884394645691,
   'toke

In [12]:
from transformers import TFAutoModelForMaskedLM, AutoTokenizer

In [14]:
tokenizer = AutoTokenizer.from_pretrained("distilroberta-base")
model = TFAutoModelForMaskedLM.from_pretrained("distilroberta-base")

All model checkpoint layers were used when initializing TFRobertaForMaskedLM.

All the layers of TFRobertaForMaskedLM were initialized from the model checkpoint at distilroberta-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForMaskedLM for predictions without further training.


In [15]:
tokenizer = AutoTokenizer.from_pretrained("distilroberta-base")
model = TFAutoModelForMaskedLM.from_pretrained("distilroberta-base")

All model checkpoint layers were used when initializing TFRobertaForMaskedLM.

All the layers of TFRobertaForMaskedLM were initialized from the model checkpoint at distilroberta-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForMaskedLM for predictions without further training.


In [17]:
vocab = tokenizer.get_vocab()
id2word = {i: word for word, i in vocab.items()}

In [18]:
sequence = f"Pizza is my {tokenizer.mask_token} food."
sequence

'Pizza is my <mask> food.'

In [19]:
input_ids = tokenizer.encode(sequence, return_tensors='tf')
input_ids

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[    0,   510, 35280,    16,   127, 50264,   689,     4,     2]])>

In [20]:
tokenizer.mask_token_id

50264

In [22]:
input_ids

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[    0,   510, 35280,    16,   127, 50264,   689,     4,     2]])>

In [23]:
input_ids[0] == tokenizer.mask_token_id

<tf.Tensor: shape=(9,), dtype=bool, numpy=array([False, False, False, False, False,  True, False, False, False])>

In [24]:
import tensorflow as tf

In [25]:
mask_token_indices = tf.where(input_ids[0] == tokenizer.mask_token_id)[0].numpy().tolist()
mask_token_indices

[5]

In [26]:
result = model(input_ids)

In [27]:
logits = result[0]
logits

<tf.Tensor: shape=(1, 9, 50265), dtype=float32, numpy=
array([[[35.35766   , -3.8330357 , 18.556173  , ...,  3.12123   ,
          5.922853  , 12.715132  ],
        [ 1.9485795 , -5.0265136 , 14.836345  , ..., -1.1891124 ,
          0.7311702 ,  0.7832576 ],
        [ 2.0384846 , -4.953379  ,  5.4868183 , ..., -3.4435925 ,
         -0.87940323, -0.41273394],
        ...,
        [-3.3596616 , -6.239405  ,  5.7364025 , ..., -1.9424853 ,
         -1.668887  , -2.7464814 ],
        [18.7403    , -5.234599  , 19.331993  , ...,  0.33183146,
          2.8348486 ,  4.3758855 ],
        [11.215204  , -5.8257084 , 28.299002  , ..., -0.9804349 ,
         -3.4882178 ,  5.4295077 ]]], dtype=float32)>

In [28]:
i = mask_token_indices[0]
i

5

In [29]:
logits.shape

TensorShape([1, 9, 50265])

In [30]:
mask_token_logits = logits[0, i, :]
mask_token_logits.shape

TensorShape([50265])

In [31]:
mask_token_logits

<tf.Tensor: shape=(50265,), dtype=float32, numpy=
array([-3.1226814 , -4.801013  ,  2.9825027 , ..., -4.36097   ,
       -4.8979836 , -0.07158422], dtype=float32)>

In [32]:
# 상위 10개
top = tf.math.top_k(mask_token_logits, k=10)
top

TopKV2(values=<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([17.85983 , 16.52289 , 15.949996, 14.083212, 13.690206, 13.487871,
       13.002301, 12.865288, 12.575063, 12.507711], dtype=float32)>, indices=<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([ 2674,  5863,  5548,  6543,  3366,  6813,  5440, 17771,  7080,
        7476])>)

In [33]:
for i in top.indices.numpy().tolist():
    print(id2word[i])

Ġfavorite
Ġcomfort
Ġfavourite
Ġsignature
Ġdream
Ġpreferred
Ġpassion
Ġstaple
Ġbreakfast
Ġeveryday


In [39]:
sequence = f"Pizza {tokenizer.mask_token} my {tokenizer.mask_token} food."
sequence

'Pizza <mask> my <mask> food.'

In [40]:
input_ids = tokenizer.encode(sequence, return_tensors="tf")

In [41]:
mask_token_indices = tf.where(input_ids[0] == tokenizer.mask_token_id)
mask_token_indices

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[3],
       [5]], dtype=int64)>

In [42]:
mask_token_indices = tf.squeeze(mask_token_indices).numpy().tolist()
mask_token_indices

[3, 5]

In [51]:
# 각 빈 칸의 가장 로짓(확률)이 높은 토큰들 출력
result = model(input_ids)
logits = result[0]
for i in mask_token_indices:
    print(f"===== {i} ====")
    mask_token_logits = logits[0, i, :]
    top = tf.math.top_k(mask_token_logits, k=10)
    for i in top.indices.numpy().tolist():
        print(id2word[i])
    print()

===== 3 ====
Ġis
Ġwas
Ġas
Ġbecomes
Ġequals
Ġfor
Ġdelivers
Ġmakes
Ġand
Ġwith

===== 5 ====
Ġfavorite
Ġcomfort
Ġfavourite
Ġjunk
Ġbreakfast
Ġlunch
Ġown
Ġsnack
Ġfried
Ġpreferred

