In [4]:
import tensorflow as tf

In [5]:
# softmax 함수에서 logit값이 같으면 확률은 같다
tf.nn.softmax([1.0, 1.0])    # 정수는 입력값 설정이 불가능하므로 실수로 입력할 것

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 0.5], dtype=float32)>

In [6]:
tf.nn.softmax([1.0, 1.0, 1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.33333334, 0.33333334, 0.33333334], dtype=float32)>

In [7]:
# softmax 함수에서 특정 logit값이 클 경우
tf.nn.softmax([1.0, 1.0, 2.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.21194156, 0.21194156, 0.57611686], dtype=float32)>

In [8]:
# 마이너스 값이 있는 경우 - 총합이 0이라 확률로 바꿀 수 없다
tf.nn.softmax([-1.0, 0.0, 1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.09003057, 0.24472848, 0.66524094], dtype=float32)>

softmax함수는 지수함수에 바탕을 두고 있다  
지수함수 : exp()  
e : 2.71828

In [9]:
tf.exp(1.0)    # e의 1승

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [10]:
tf.exp(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=7.389056>

In [11]:
tf.exp(0.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [12]:
tf.exp(-1.0)    # 1/2.7 즉, 역수로 나눠주게 된다

<tf.Tensor: shape=(), dtype=float32, numpy=0.36787945>

In [13]:
tf.exp([-1.0, 0.0, 1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.36787945, 1.        , 2.7182817 ], dtype=float32)>

In [14]:
tf.reduce_sum(tf.exp([-1.0, 0.0, 1.0]))    # numpy에 대한 총합

<tf.Tensor: shape=(), dtype=float32, numpy=4.086161>

In [15]:
tf.exp([-1.0, 0.0, 1.0]) / tf.reduce_sum(tf.exp([-1.0, 0.0, 1.0]))    # 총합을 나눔

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.09003058, 0.24472848, 0.66524094], dtype=float32)>

In [20]:
# 시그모이드 함수
tf.nn.sigmoid(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7310586>

In [16]:
tf.nn.sigmoid(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8807971>

In [17]:
tf.nn.softmax([0.0, 2.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.11920291, 0.880797  ], dtype=float32)>